"""create deployments table

Revision ID: 1eda7af2ba07
Revises: d64f864d2079
Create Date: 2026-09-15 21:56:33.870670

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1eda7af2ba07'
down_revision: str | Sequence[str] | None = 'd64f864d2079'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), server_default='DEPLOYING', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'environment', name='uq_deployments_model_version_environment')
    )
    op.create_index(op.f('ix_deployments_environment'), 'deployments', ['environment'], unique=False)
    op.create_index(op.f('ix_deployments_model_version_id'), 'deployments', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_deployments_state'), 'deployments', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_state'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_model_version_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
