"""add deployment targets

Revision ID: eca2e545b4c6
Revises: 1eda7af2ba07
Create Date: 2026-09-15 22:37:14.692007

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eca2e545b4c6'
down_revision: str | Sequence[str] | None = '1eda7af2ba07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_targets',
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('active_deployment_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_deployment_id'], ['deployments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('environment'),
    sa.UniqueConstraint('active_deployment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_targets')
    # ### end Alembic commands ###
