const state={authConfig:null,identity:null,workspaces:[],selectedWorkspace:null,models:[],modelVersions:new Map(),deployments:[],targets:[],runtimes:{in_process:[],external:[]},health:{external:[]},keys:[]};
function esc(v){const e=document.createElement("div");e.textContent=v==null?"":String(v);return e.innerHTML}
function cookie(n){const p=n+"=";const i=document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith(p));return i?i.slice(p.length):""}
function headers(method,body,skip){const h={};if(body)h["Content-Type"]="application/json";if(!skip&&state.selectedWorkspace)h["X-ModelForge-Workspace"]=state.selectedWorkspace;if(["POST","PUT","PATCH","DELETE"].includes(String(method||"GET").toUpperCase())){const c=decodeURIComponent(cookie("mf_csrf"));if(c)h["X-ModelForge-CSRF"]=c}return h}
async function api(path,options){const o=Object.assign({method:"GET"},options||{});const body=o.body!==undefined&&o.body!==null;o.credentials="same-origin";o.headers=Object.assign(headers(o.method,body,o.skipWorkspace),o.headers||{});delete o.skipWorkspace;const r=await fetch(path,o);const ct=r.headers.get("content-type")||"";const p=ct.includes("application/json")?await r.json():await r.text();if(!r.ok){const e=new Error(p&&p.detail?p.detail:String(p||r.statusText));e.status=r.status;throw e}return p}
function toast(msg,err){const e=document.getElementById("toast");e.textContent=msg;e.className="toast show"+(err?" error":"");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.className="toast",3000)}
function badge(v){const n=String(v||"unknown").toLowerCase();return '<span class="badge '+esc(n)+'">'+esc(v||"unknown")+"</span>"}
function initials(v){return String(v||"M").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join("")||"M"}
function canKeys(){return state.identity&&["admin","owner"].includes(state.identity.role)}
async function identity(){state.authConfig=await api("/auth/config",{skipWorkspace:true});try{state.workspaces=await api("/workspaces",{skipWorkspace:true});const remembered=localStorage.getItem("modelforge.workspace");const match=state.workspaces.find(x=>x.slug===remembered);state.selectedWorkspace=match?match.slug:(state.workspaces[0]?state.workspaces[0].slug:null);state.identity=await api("/auth/me");renderIdentity();return true}catch(e){if(e.status===401&&state.authConfig.browser_login_enabled){document.getElementById("auth-gate").classList.add("show");return false}throw e}}
function renderIdentity(){const i=state.identity||{};const w=state.workspaces.find(x=>x.slug===state.selectedWorkspace);const s=document.getElementById("workspace-select");s.innerHTML="";state.workspaces.forEach(x=>{const o=document.createElement("option");o.value=x.slug;o.textContent=x.name;o.selected=x.slug===state.selectedWorkspace;s.appendChild(o)});document.getElementById("workspace-subtitle").textContent=(w?w.name:i.workspace_slug||"Workspace")+" · "+(i.role||"member");const name=i.display_name||i.email||(i.auth_type==="self_hosted"?"Self-hosted operator":"ModelForge user");document.getElementById("user-name").textContent=name;document.getElementById("user-role").textContent=i.role||"member";document.getElementById("avatar").textContent=initials(name);document.getElementById("new-workspace").hidden=!i.user_id;document.getElementById("logout-button").hidden=i.auth_type==="self_hosted"}
async function versions(){state.modelVersions=new Map(await Promise.all(state.models.map(async m=>{try{return[m.id,await api("/models/"+m.id+"/versions")]}catch(e){return[m.id,[]]}})))}
async function targets(){const env=[...new Set(state.deployments.map(x=>x.environment))];state.targets=(await Promise.all(env.map(async x=>{try{return await api("/deployment-targets/"+encodeURIComponent(x))}catch(e){return null}}))).filter(Boolean)}
async function keys(){state.keys=canKeys()?await api("/api-keys"):[]}
async function refresh(){const b=document.getElementById("refresh-button");b.disabled=true;try{const r=await Promise.all([api("/health",{skipWorkspace:true}),api("/ready",{skipWorkspace:true}),api("/models"),api("/deployments"),api("/runtimes"),api("/runtimes/health"),api("/auth/me")]);state.models=r[2];state.deployments=r[3];state.runtimes=r[4];state.health=r[5];state.identity=r[6];await Promise.all([versions(),targets(),keys()]);render(r[1]);renderIdentity();document.getElementById("api-dot").classList.add("ok");document.getElementById("api-status").textContent="API healthy"}catch(e){if(e.status===401&&state.authConfig&&state.authConfig.browser_login_enabled)document.getElementById("auth-gate").classList.add("show");else toast(e.message,true)}finally{b.disabled=false}}
function render(readiness){const av=[...state.modelVersions.values()].flat(),ext=state.runtimes.external||[],inp=state.runtimes.in_process||[],healthy=(state.health.external||[]).filter(x=>x.status==="healthy").length;document.getElementById("readiness").textContent=readiness.status||"unknown";document.getElementById("external-health").textContent=ext.length?healthy+"/"+ext.length+" runtimes healthy":"In-process runtimes only";document.getElementById("last-refresh").textContent=new Date().toLocaleTimeString();document.getElementById("models-count").textContent=state.models.length;document.getElementById("versions-count").textContent=av.length;document.getElementById("deployments-count").textContent=state.deployments.length;document.getElementById("environments-count").textContent=state.targets.length;document.getElementById("canaries-count").textContent=state.deployments.filter(x=>x.state==="CANARY").length;document.getElementById("runtimes-count").textContent=ext.length+inp.length;document.getElementById("onboarding").hidden=state.models.length>0;const ok=ext.length===0||healthy===ext.length;document.getElementById("runtime-dot").classList.toggle("ok",ok);document.getElementById("runtime-status").textContent=ok?"Runtimes healthy":"Runtime attention";renderModels();renderDeployments();renderTargets();renderRuntimes();renderKeys()}
function renderModels(){const b=document.getElementById("model-body");b.innerHTML="";state.models.forEach(m=>{const v=state.modelVersions.get(m.id)||[],f=[...new Set(v.map(x=>x.framework))].join(", ")||"—",r=document.createElement("tr");r.innerHTML="<td><strong>"+esc(m.name)+"</strong><div class='muted'>#"+m.id+"</div></td><td class='muted'>"+esc(m.description||"—")+"</td><td>"+v.length+"</td><td>"+esc(f)+"</td>";b.appendChild(r)});document.getElementById("model-empty").hidden=state.models.length!==0}
function act(label,a,id,d){return"<button class='btn small"+(d?" danger":"")+"' data-action='"+a+"' data-id='"+id+"'>"+label+"</button>"}
function dActions(d){const x=[];if(d.state==="DEPLOYING"){x.push(act("Promote","promote",d.id));x.push(act("Canary","canary-start",d.id))}else if(d.state==="CANARY"){x.push(act("Weight","canary-weight",d.id));x.push(act("Promote canary","canary-promote",d.id));x.push(act("Abort","canary-abort",d.id,true))}else if(d.state==="SUPERSEDED")x.push(act("Rollback","rollback",d.id));return x.length?"<div class='actions'>"+x.join("")+"</div>":"—"}
function renderDeployments(){const b=document.getElementById("deployment-body");b.innerHTML="";state.deployments.slice().reverse().forEach(d=>{const r=document.createElement("tr");r.innerHTML="<td>#"+d.id+"</td><td><strong>"+esc(d.environment)+"</strong></td><td>#"+d.model_version_id+"</td><td>"+badge(d.state)+"</td><td>"+dActions(d)+"</td>";b.appendChild(r)});document.getElementById("deployment-empty").hidden=state.deployments.length!==0}
function renderTargets(){const b=document.getElementById("target-body");b.innerHTML="";state.targets.forEach(t=>{const r=document.createElement("tr");r.innerHTML="<td><strong>"+esc(t.environment)+"</strong></td><td>#"+t.active_deployment_id+"</td><td>"+(t.canary_deployment_id?"#"+t.canary_deployment_id:"—")+"</td><td>"+(t.canary_deployment_id?t.canary_weight+"%":"—")+"</td>";b.appendChild(r)});document.getElementById("target-empty").hidden=state.targets.length!==0}
function renderRuntimes(){const b=document.getElementById("runtime-body");b.innerHTML="";const hm=new Map((state.health.external||[]).map(x=>[x.framework,x]));(state.runtimes.in_process||[]).forEach(x=>{const r=document.createElement("tr");r.innerHTML="<td><strong>"+esc(x.framework)+"</strong></td><td>in-process</td><td>"+badge("healthy")+"</td><td>0</td>";b.appendChild(r)});(state.runtimes.external||[]).forEach(x=>{const h=hm.get(x.framework)||{},r=document.createElement("tr");r.innerHTML="<td><strong>"+esc(x.framework)+"</strong><div class='muted'>"+esc(x.runtime||"")+"</div></td><td>external</td><td>"+badge(h.status||x.circuit_state)+"</td><td>"+(x.consecutive_failures||0)+"</td>";b.appendChild(r)});document.getElementById("runtime-empty").hidden=((state.runtimes.in_process||[]).length+(state.runtimes.external||[]).length)!==0}
function fmt(v){return v?new Date(v).toLocaleString():"Never"}
function renderKeys(){const b=document.getElementById("key-body");b.innerHTML="";const ok=canKeys();document.getElementById("create-key").hidden=!ok;document.getElementById("key-forbidden").hidden=ok;document.getElementById("key-empty").hidden=!ok||state.keys.length!==0;if(!ok)return;state.keys.forEach(k=>{const r=document.createElement("tr");r.innerHTML="<td><strong>"+esc(k.name)+"</strong><div class='muted'>"+(k.revoked_at?"Revoked":"Active")+"</div></td><td class='keyprefix'>"+esc(k.key_prefix)+"…</td><td>"+badge(k.role)+"</td><td class='muted'>"+esc(fmt(k.created_at))+"</td><td class='muted'>"+esc(fmt(k.last_used_at))+"</td><td>"+(k.revoked_at?"—":"<button class='btn small danger' data-revoke='"+k.id+"'>Revoke</button>")+"</td>";b.appendChild(r)})}
async function mutate(path,method,payload,msg){try{await api(path,{method:method||"POST",body:payload?JSON.stringify(payload):undefined});toast(msg,false);await refresh()}catch(e){toast(e.message,true)}}
document.getElementById("deployment-body").addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const id=b.dataset.id,a=b.dataset.action;if(a==="promote")return mutate("/deployments/"+id+"/promote","POST",null,"Deployment promoted.");if(a==="rollback")return mutate("/deployments/"+id+"/rollback","POST",null,"Deployment rolled back.");if(a==="canary-start"){const w=Number(prompt("Canary traffic percentage (1-99)","10"));if(Number.isInteger(w))return mutate("/deployments/"+id+"/canary","POST",{weight:w},"Canary started.")}if(a==="canary-weight"){const w=Number(prompt("New canary traffic percentage (1-99)","20"));if(Number.isInteger(w))return mutate("/deployments/"+id+"/canary","PATCH",{weight:w},"Canary weight updated.")}if(a==="canary-promote"&&confirm("Promote this canary to stable?"))return mutate("/deployments/"+id+"/canary/promote","POST",null,"Canary promoted.");if(a==="canary-abort"){const r=prompt("Reason for aborting this canary","Operator aborted canary from dashboard.");if(r)return mutate("/deployments/"+id+"/canary/abort","POST",{reason:r},"Canary aborted.")}})
document.getElementById("predict-button").addEventListener("click",async()=>{const out=document.getElementById("prediction-output");let input;try{input=JSON.parse(document.getElementById("inputs").value.trim())}catch(e){out.textContent="Invalid JSON input: "+e.message;return}out.textContent="Running prediction…";try{out.textContent=JSON.stringify(await api("/predict",{method:"POST",body:JSON.stringify({environment:document.getElementById("environment").value.trim(),inputs:input})}),null,2)}catch(e){out.textContent="Prediction failed: "+e.message}})
document.getElementById("workspace-select").addEventListener("change",async e=>{state.selectedWorkspace=e.target.value;localStorage.setItem("modelforge.workspace",state.selectedWorkspace);await refresh()})
document.getElementById("new-workspace").addEventListener("click",()=>document.getElementById("workspace-dialog").showModal())
document.getElementById("workspace-name").addEventListener("input",e=>{document.getElementById("workspace-slug").value=e.target.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)})
document.getElementById("workspace-form").addEventListener("submit",async e=>{e.preventDefault();try{const w=await api("/workspaces",{method:"POST",body:JSON.stringify({name:document.getElementById("workspace-name").value.trim(),slug:document.getElementById("workspace-slug").value.trim()})});state.workspaces=await api("/workspaces",{skipWorkspace:true});state.selectedWorkspace=w.slug;localStorage.setItem("modelforge.workspace",w.slug);document.getElementById("workspace-dialog").close();renderIdentity();await refresh();toast("Workspace created.",false)}catch(x){toast(x.message,true)}})
document.getElementById("create-key").addEventListener("click",()=>document.getElementById("key-dialog").showModal())
document.getElementById("key-form").addEventListener("submit",async e=>{e.preventDefault();try{const k=await api("/api-keys",{method:"POST",body:JSON.stringify({name:document.getElementById("key-name").value.trim(),role:document.getElementById("key-role").value})});document.getElementById("key-dialog").close();document.getElementById("secret-value").textContent=k.secret;document.getElementById("secret-dialog").showModal();await keys();renderKeys()}catch(x){toast(x.message,true)}})
document.getElementById("key-body").addEventListener("click",async e=>{const b=e.target.closest("button[data-revoke]");if(!b||!confirm("Revoke this API key? Existing clients will immediately lose access."))return;try{await api("/api-keys/"+b.dataset.revoke,{method:"DELETE"});await keys();renderKeys();toast("API key revoked.",false)}catch(x){toast(x.message,true)}})
document.getElementById("copy-secret").addEventListener("click",async e=>{e.preventDefault();await navigator.clipboard.writeText(document.getElementById("secret-value").textContent);toast("API key copied.",false)})
document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();document.getElementById(b.dataset.close).close()}))
document.getElementById("logout-button").addEventListener("click",async()=>{try{await api("/auth/logout",{method:"POST",skipWorkspace:true});location.assign("/")}catch(e){toast(e.message,true)}})
document.getElementById("refresh-button").addEventListener("click",refresh)
;(async()=>{try{if(await identity()){await refresh();setInterval(refresh,15000)}}catch(e){toast(e.message,true)}})()
